name: run-tests

on: 
    push:
        branches:
            - main
jobs:
    Run-unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependency
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests
              run:
                python -m unittest tests/test.py

            



